### ISSUE TITLE
mvn verify

### ISSUE THREAD

**Issue by sixcorners** [heroku/heroku-buildpack-java#105]
In /bin/test would it be a good idea to call "mvn verify" instead of "mvn test"? If you have integration tests with the [maven-failsafe-plugin](https://maven.apache.org/surefire/maven-failsafe-plugin/) then they won't run with just the test goal.

**Comment by sixcorners** [comment]
I kind of don't know that much about buildpacks.. What determines the set of things that can be in bin/? Is it possible or a good idea to add a /bin/integration-test or a /bin/verify?

**Comment by jkutner** [comment]
The [buildpack API](https://devcenter.heroku.com/articles/buildpack-api) defines the scripts that can be in `bin/`. I think we do need a mechanism to allow you to choose between `mvn test` and `mvn verify`.  But I'm not sure of the best way yet. If you need this capability quickly, I think [setting your scripts in app.json](https://devcenter.heroku.com/articles/heroku-ci#specifying-custom-test-commands-the-scripts-key-example) is the best option for now. 

Thanks for your patience. We'll try to resolve this sooner rather than later.
