### ISSUE TITLE
Query : how to enable gzip compression?

### ISSUE THREAD

**Issue by mandatorySuicide** [heroku/heroku-buildpack-java#99]
I added this in the application.properties file of my spring boot app. 
server.compression.enabled=true
In the localhost, gzip is working correctly. But in the heroku server, gzip header is missing and file is not being compressed. Any clue on how I can enable gzip for my java app? I am using jar deploy and no Procfile.

**Comment by jkutner** [comment]
You may want to inspect the dyno process with [`heroku java:jconsole`](https://devcenter.heroku.com/articles/exec#using-java-debugging-tools) to ensure the `server.compression.enabled` option is picked up. Then you may need to set `server.compression.mime-types` to something like "text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json". Otherwise it should work.
